### ISSUE TITLE
GET Suggested Jobs API

### ISSUE THREAD

**Issue by nhtoby311** [vantoan19/CodeToGive2022_Backend#2]
- Type: GET
- Use to display Suggested Jobs for user
- NOTE: The array return should be sorted, descending value from highest `match_value` to lowest `match_value`
- Schema: 
```typescript
export default interface IJob {
  id: number
  title: string
  match_value: number
  details: {
    company_name: string
    about: string
    description: string
  }
  image?: string
}
```
- Desired object: 
```yaml
[
  {
    id: 1,
    title: "Shop assistant", 
    match_value: 72,     
    details: {
      company_name: "Canary inc.",
      about: "This company is legit, no cap, 4real",
      description: "U will need to do this, and that, this skill, that skill"
    },
    image: "https://images.unsplash.com/photo-1664335183382-435abfae46b0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80"
  },
  ...
]
```
- Imagined API: `/api/{uuid}/suggested-jobs`
- Use for this design: (Design is not finalized)
![image](https://user-images.githubusercontent.com/52330522/192525745-77f6e3be-c108-4b34-bfcb-cf8dd0fcf9ea.png)
